/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'fullName' : IDL.Text,
});
export const CustomizationSettings = IDL.Record({
  'theme' : IDL.Text,
  'primaryColor' : IDL.Text,
  'logoUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelPremium' : IDL.Func([], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomizationSettings' : IDL.Func(
      [],
      [IDL.Opt(CustomizationSettings)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerPremium' : IDL.Func([], [IDL.Bool], ['query']),
  'likeTemplatePost' : IDL.Func([IDL.Nat], [], []),
  'loginAdmin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'logoutAdmin' : IDL.Func([], [], []),
  'repostTemplate' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveCustomizationSettings' : IDL.Func([CustomizationSettings], [], []),
  'setUserPremium' : IDL.Func([IDL.Principal], [], []),
  'upgradeToPremium' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'fullName' : IDL.Text,
  });
  const CustomizationSettings = IDL.Record({
    'theme' : IDL.Text,
    'primaryColor' : IDL.Text,
    'logoUrl' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelPremium' : IDL.Func([], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomizationSettings' : IDL.Func(
        [],
        [IDL.Opt(CustomizationSettings)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerPremium' : IDL.Func([], [IDL.Bool], ['query']),
    'likeTemplatePost' : IDL.Func([IDL.Nat], [], []),
    'loginAdmin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'logoutAdmin' : IDL.Func([], [], []),
    'repostTemplate' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveCustomizationSettings' : IDL.Func([CustomizationSettings], [], []),
    'setUserPremium' : IDL.Func([IDL.Principal], [], []),
    'upgradeToPremium' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };