/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'fullName' : IDL.Text,
});
export const CustomizationSettings = IDL.Record({
  'theme' : IDL.Text,
  'primaryColor' : IDL.Text,
  'logoUrl' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const VideoFile = IDL.Record({
  'id' : IDL.Nat,
  'contentType' : IDL.Text,
  'owner' : IDL.Principal,
  'templateId' : IDL.Nat,
  'blob' : ExternalBlob,
  'fileName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelPremium' : IDL.Func([], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomizationSettings' : IDL.Func(
      [],
      [IDL.Opt(CustomizationSettings)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVideoFile' : IDL.Func([IDL.Nat], [IDL.Opt(VideoFile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerPremium' : IDL.Func([], [IDL.Bool], ['query']),
  'likeTemplatePost' : IDL.Func([IDL.Nat], [], []),
  'loginAdmin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'logoutAdmin' : IDL.Func([], [], []),
  'repostTemplate' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveCustomizationSettings' : IDL.Func([CustomizationSettings], [], []),
  'setUserPremium' : IDL.Func([IDL.Principal], [], []),
  'upgradeToPremium' : IDL.Func([], [], []),
  'uploadTemplateVideo' : IDL.Func(
      [IDL.Text, IDL.Text, ExternalBlob],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'fullName' : IDL.Text,
  });
  const CustomizationSettings = IDL.Record({
    'theme' : IDL.Text,
    'primaryColor' : IDL.Text,
    'logoUrl' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const VideoFile = IDL.Record({
    'id' : IDL.Nat,
    'contentType' : IDL.Text,
    'owner' : IDL.Principal,
    'templateId' : IDL.Nat,
    'blob' : ExternalBlob,
    'fileName' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelPremium' : IDL.Func([], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomizationSettings' : IDL.Func(
        [],
        [IDL.Opt(CustomizationSettings)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVideoFile' : IDL.Func([IDL.Nat], [IDL.Opt(VideoFile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerPremium' : IDL.Func([], [IDL.Bool], ['query']),
    'likeTemplatePost' : IDL.Func([IDL.Nat], [], []),
    'loginAdmin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'logoutAdmin' : IDL.Func([], [], []),
    'repostTemplate' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveCustomizationSettings' : IDL.Func([CustomizationSettings], [], []),
    'setUserPremium' : IDL.Func([IDL.Principal], [], []),
    'upgradeToPremium' : IDL.Func([], [], []),
    'uploadTemplateVideo' : IDL.Func(
        [IDL.Text, IDL.Text, ExternalBlob],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };